# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sofoniasserverless
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverlessapi
# "service" is the name of this project. This will also be added to your AWS resource names.
service: myServerless

provider:
  name: aws
  runtime: nodejs20.x
  profile: sofoniasserverless

plugins:
    - Serverless-s3-sync
    - Serverless-webpack # Added serverless-webpack plugin

package: 
    individually: true

custom:
  s3Sync:
     - bucketName: sofoniasserverless22795245
       localDir: UploadData
  webpack: # Added Webpack custom configuration
    webpackConfig: ./webpack.config.js
    includeModules: true

#functions:
 # hello:
  #  handler: handler.hello
   # events:
    #  - httpApi:
     #     path: /
      #    method: get

functions:
    getUser:
        handler: lambdas/getUser.handler
        events:
          - http:
              path: get-user/{ID}
              method: get
              cors: true

resources:
    Resources:
        DemoBucketUpload:
           Type: AWS::S3::Bucket
           Properties:
              BucketName: sofoniasserverless22795245
